In [3]:
list_a=[1,3,5,7,9]
list_b=[3,5,6,7,9]
list_a+list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [11]:
import numpy as np
array_a=np.array([1,3,5,7,9])
array_b=np.array([3,5,6,7,9])
type(array_a)
array_a+array_b


array([ 4,  8, 11, 14, 18])

In [16]:
import numpy as np
l=[[1,2,3],[2,3,4]]
array=np.array(l)
array.ndim,array.shape,array.size,array.dtype

(2, (2, 3), 6, dtype('int64'))

In [34]:
import numpy as np
np.random.randn(10,5)

array([[-0.42234841, -0.9302822 ,  1.00297415,  1.1209148 , -1.36589847],
       [ 0.07713246,  0.6058436 ,  1.84190779,  1.29950082,  0.61988715],
       [ 0.67792035, -0.90921882, -0.30368738, -0.73870608,  0.00662653],
       [ 0.7442891 , -0.92292192,  1.44831659, -0.48613063,  1.0658277 ],
       [-0.94531342, -0.50129151,  1.00212564,  1.99401665, -0.91217038],
       [-0.47885227,  0.3008749 , -0.35033094, -0.9197028 , -0.78329563],
       [-0.20593974,  0.06979519, -1.36128495, -0.54981503,  1.16532977],
       [ 0.56425284, -2.96689881, -0.59638043, -0.5296174 , -0.56535508],
       [-1.86611749, -0.0950073 ,  1.26449191, -0.03161876, -2.12123465],
       [-1.9055948 ,  1.18608343,  0.64865916, -0.81896292, -0.30881424]])

In [35]:
#50個學生,每個學生有5個分數(50-100)
import numpy as np
scores=np.random.randint(50,101,size=(50,5))
scores

array([[ 75,  70,  71,  88,  72],
       [ 69,  53,  73,  62,  57],
       [ 53,  54,  77,  97,  93],
       [ 96,  74,  72,  86,  79],
       [ 73,  90,  56,  92,  66],
       [ 76,  52,  97,  93,  99],
       [ 95,  87,  99,  54,  98],
       [ 73,  68,  74,  94,  51],
       [ 81,  62,  60,  78,  63],
       [ 65, 100,  72,  53,  64],
       [ 83,  51,  96,  52,  68],
       [ 52,  92,  54,  84,  82],
       [ 80,  67,  86,  51,  55],
       [ 77,  63,  73,  50,  68],
       [ 67,  79,  88,  62,  50],
       [ 79,  68,  72,  69,  83],
       [ 78,  57, 100,  59,  50],
       [ 80,  60,  67,  89,  98],
       [ 75,  81,  82,  98,  76],
       [ 86,  83,  73,  98,  93],
       [ 70,  84,  72,  89,  64],
       [ 63,  62,  93,  75,  97],
       [ 51,  65,  82,  52,  63],
       [ 84,  56,  84,  96,  50],
       [ 84,  58,  86,  85,  54],
       [ 94,  73,  76,  78,  84],
       [ 81,  68,  84,  53,  91],
       [ 77,  78,  56,  73,  63],
       [ 59,  99,  62,  57,  73],
       [ 54,  

In [43]:
#第一個學生
scores[0,:]


array([75, 70, 71, 88, 72])

In [44]:
#前5個學生
scores[:5,:]

array([[75, 70, 71, 88, 72],
       [69, 53, 73, 62, 57],
       [53, 54, 77, 97, 93],
       [96, 74, 72, 86, 79],
       [73, 90, 56, 92, 66]])

In [45]:
#最後5個學生
scores[-5:,:]

array([[ 75,  67,  55,  55,  56],
       [ 90,  62, 100,  55,  96],
       [ 86,  64,  51,  78,  69],
       [ 53,  84,  73,  53,  97],
       [ 82,  77,  83,  68,  62]])

In [41]:
#全班第一科的分數
scores[:,0]

array([ 75,  69,  53,  96,  73,  76,  95,  73,  81,  65,  83,  52,  80,
        77,  67,  79,  78,  80,  75,  86,  70,  63,  51,  84,  84,  94,
        81,  77,  59,  54,  52,  84,  96,  66,  84, 100,  52,  69,  92,
        64,  69,  52,  66,  70,  51,  75,  90,  86,  53,  82])

In [42]:
#全班第2科的分數
scores[:,1]

array([ 70,  53,  54,  74,  90,  52,  87,  68,  62, 100,  51,  92,  67,
        63,  79,  68,  57,  60,  81,  83,  84,  62,  65,  56,  58,  73,
        68,  78,  99,  59,  83,  94,  88,  63,  57,  81,  52,  97,  66,
        71,  71,  50,  56,  81,  75,  67,  62,  64,  84,  77])

In [47]:
#每位學生的總分
total=scores[:,0]+scores[:,1]+scores[:,2]+scores[:,3]+scores[:,4]
total

array([376, 314, 374, 407, 377, 417, 433, 360, 344, 354, 350, 364, 339,
       331, 346, 371, 344, 394, 412, 433, 379, 390, 313, 370, 367, 405,
       377, 347, 350, 349, 369, 373, 431, 340, 399, 425, 294, 410, 377,
       343, 388, 324, 356, 340, 329, 308, 403, 348, 360, 372])

In [48]:
#使用統計的方法
#每個學生的總分
np.sum(scores,axis=1)

array([376, 314, 374, 407, 377, 417, 433, 360, 344, 354, 350, 364, 339,
       331, 346, 371, 344, 394, 412, 433, 379, 390, 313, 370, 367, 405,
       377, 347, 350, 349, 369, 373, 431, 340, 399, 425, 294, 410, 377,
       343, 388, 324, 356, 340, 329, 308, 403, 348, 360, 372])

In [49]:
#每個學生的平均
np.median(scores,axis=1)

array([72., 62., 77., 79., 73., 93., 95., 73., 63., 65., 68., 82., 67.,
       68., 67., 72., 59., 80., 81., 86., 72., 75., 63., 84., 84., 78.,
       81., 73., 62., 65., 73., 71., 92., 63., 84., 81., 52., 88., 69.,
       69., 71., 52., 70., 70., 73., 56., 90., 69., 73., 77.])